### ISSUE TITLE
Docs: update README on how to install the package

### ISSUE THREAD

**Issue by shdq** [shdq/spartak-ui#60]
`Spartak UI` was published to the `npm` registry.

This required updating the project `README` with a new section on how to install it using `npm` and `yarn` package managers.

🙌 Contributions are welcome! Leave a comment if you want to help with this issue.

**Comment by jaswanthg76** [comment]
'm new to open-sourcing and I have no clue about what I should be doing. Can anyone guide me? I have basic knowledge of java
let me know in which way I can help you.

**Comment by jaswanthg76** [comment]
I'm new to open-sourcing and I have no clue about what I should be doing. Can anyone guide me? I have basic knowledge of java
let me know in which way I can help you.

**Comment by shdq** [comment]
Hello @jaswanthg76! Thanks for your interest in contributing to the project.

I'll guide you through your first contribution.

This issue doesn't require coding, but to update a markdown file – [`README.md`](https://github.com/shdq/spartak-ui/blob/main/README.md).

1. Open the link above and click on the `Raw` button and get familiar with the structure of the document.
2. Read [this documentation page](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) on how to write and format markdown files.
3. This project is for the `JavaScript` ecosystem and there are two widespread package managers [npm](https://npmjs.com) and [yarn](https://yarnpkg.com/). [Read the docs](https://docs.npmjs.com/downloading-and-installing-packages-locally) on how to install packages from `npm` registry. You can also look at the other JavaScript projects and what they "How to install" sections say.

In the end, we should have two commands for `npm` and `yarn` package managers that install the `Spartak UI` package from the registry.

When we agree on the content for a new section, I will help you to create a pull request and contribute.

Let me know if you have any questions.

**Comment by Hari0006** [comment]
@shdq : Since no one is assigned to this task till now, I have completed this task and created a new pull request. Please review.

https://github.com/shdq/spartak-ui/pull/69

**Comment by shdq** [comment]
Welcome @Hari0006 👋

Thank you for your time and willingness to contribute. Although it is a minor change, I would appreciate it if you could discuss your proposed changes here in the issue before opening a pull request. This will help prevent the rejection of your future contributions not only in this project but also in others.

I will review your pull request and provide comments there, if necessary. Let's continue our conversation in the pull request.

**Comment by Hari0006** [comment]
@shdq : Sure, I will follow this best Practice in future contributions.

**Comment by shdq** [comment]
@Hari0006 congratulations on your first contribution! 🎉🎊

By making this contribution, you have not only added value to the project but have also become an integral part of the open-source community. I encourage you to continue exploring and learning in this exciting world of software development.

Once again, congratulations on this achievement, and thank you for being a part of our growing community of developers. Keep up the fantastic work! 👍
